"use client"

import { ServiceCard } from "@/components/it-services/service/service-card"
import { Button } from "@/components/ui/button"
import { useMemo, useState, useEffect } from "react"
import { useSearchParams } from "next/navigation"

// Subcategories aligned with components/it-services/sections/search/sub-categories.tsx
const SUBCATEGORY_TITLES: Record<string, string[]> = {
  "Graphics & Design": [
    "Logo Design", "Brand Style Guides", "Illustration", "Image Editing",
    "Business Cards", "Social Posts", "Presentation Design", "Packaging",
    "Book Covers", "Infographics", "T‑Shirt Design", "UI Mockups",
  ],
  "Digital Marketing": [
    "Social Media Marketing", "SEO", "Email Marketing", "Influencer Marketing",
    "PPC Campaigns", "Content Marketing", "Affiliate Marketing", "ASO",
    "Analytics Setup", "Funnel Design", "Reputation Mgmt", "Community Growth",
  ],
  "Writing & Translation": [
    "Copywriting", "Translation", "Blog Posts", "Technical Writing",
    "Proofreading", "Product Descriptions", "UX Writing", "Resume & CV",
    "Scriptwriting", "White Papers", "Press Releases", "Subtitles",
  ],
  "Video & Animation": [
    "Video Editing", "Short Ads", "Product Shoots", "Motion Graphics",
    "2D Animation", "3D Animation", "Logo Animation", "Color Grading",
    "Captions", "YouTube Editing", "Reels/TikTok", "Storyboards",
  ],
  "Music & Audio": [
    "Music Production", "Voice Over", "Mix & Master", "Sound Design",
    "Podcast Editing", "Jingles", "Audiobooks", "SFX Packs",
    "Music Lessons", "Tuning & Timing", "Dialogue Cleanup", "Arrangement",
  ],
  "Programming & Tech": [
    "Web Development", "Backend APIs", "Databases", "Mobile Apps",
    "DevOps & CI/CD", "Cloud & Infra", "Testing & QA", "AI/ML",
    "Data Engineering", "Cybersecurity", "WordPress", "Shopify",
  ],
  Business: [
    "Business Plans", "Market Research", "Project Management", "Legal Consulting",
    "Financial Modeling", "Pitch Decks", "HR Consulting", "Sales Strategy",
    "Customer Support", "Bookkeeping", "Virtual Assistant", "Operations",
  ],
  Lifestyle: [
    "Wellness Coaching", "Fitness Training", "Nutrition", "Personal Growth",
    "Mindfulness", "Language Lessons", "Crafts & Hobbies", "Photography",
    "Home Organization", "Travel Planning", "Gardening", "Parenting",
  ],
  "Trending Services": [
    "AI Integrations", "UGC Content", "Short-form Video", "Brand Revamps",
    "Chatbots", "No-code Apps", "Webflow", "Carousel Design",
    "Landing Pages", "Newsletter", "Micro SaaS", "Prompt Engineering",
  ],
}

// Map granular service categories to their main categories used by the subcategory list
const SERVICE_CATEGORY_TO_MAIN: Record<string, string> = {
  "Design & Creative": "Graphics & Design",
  "Art & Illustration": "Graphics & Design",
  "Web & App Design": "Graphics & Design",
  Marketing: "Digital Marketing",
}

function pickSubCategory(serviceCategory: string, seed: number): string {
  const mainCategory = SERVICE_CATEGORY_TO_MAIN[serviceCategory] || serviceCategory
  const list = SUBCATEGORY_TITLES[mainCategory]
  if (!list || list.length === 0) return "General"
  const index = seed % list.length
  return list[index]
}

const baseServices = [
  {
    id: 1,
    image: "https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&w=600",
    category: "Graphics & Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Wanda Runo",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    price: 983,
  },
  {
    id: 2,
    image: "https://images.pexels.com/photos/1103970/pexels-photo-1103970.jpeg?auto=compress&w=600",
    category: "Graphics & Design",
    title: "I will create modern flat design illustration",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 3,
    image: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&w=600",
    category: "Graphics & Design",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Sophie Lee",
      avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    },
    price: 983,
  },
  {
    id: 4,
    image: "https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&w=600",
    category: "Graphics & Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  {
    id: 5,
    image: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&w=600",
    category: "Graphics & Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Mia Chen",
      avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    price: 983,
  },
  {
    id: 6,
    image: "https://images.pexels.com/photos/3861972/pexels-photo-3861972.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Wanda Runo",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    price: 983,
  },
  {
    id: 7,
    image: "https://images.pexels.com/photos/3861973/pexels-photo-3861973.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 8,
    image: "https://images.pexels.com/photos/3861974/pexels-photo-3861974.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  {
    id: 9,
    image: "https://images.pexels.com/photos/3861975/pexels-photo-3861975.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Mia Chen",
      avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    price: 983,
  },
  {
    id: 10,
    image: "https://images.pexels.com/photos/3861976/pexels-photo-3861976.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Sophie Lee",
      avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    },
    price: 983,
  },
  {
    id: 11,
    image: "https://images.pexels.com/photos/3861977/pexels-photo-3861977.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 12,
    image: "https://images.pexels.com/photos/3861978/pexels-photo-3861978.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  // Additional services for load more functionality
  {
    id: 13,
    image: "https://images.pexels.com/photos/3861979/pexels-photo-3861979.jpeg?auto=compress&w=600",
    category: "Digital Marketing",
    title: "I will create social media marketing campaigns",
    rating: 4.9,
    reviews: 156,
    author: {
      name: "Emma Wilson",
      avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    },
    price: 450,
  },
  {
    id: 14,
    image: "https://images.pexels.com/photos/3861980/pexels-photo-3861980.jpeg?auto=compress&w=600",
    category: "Writing & Translation",
    title: "I will write professional content for your website",
    rating: 4.8,
    reviews: 203,
    author: {
      name: "James Smith",
      avatar: "https://randomuser.me/api/portraits/men/15.jpg",
    },
    price: 120,
  },
  {
    id: 15,
    image: "https://images.pexels.com/photos/3861981/pexels-photo-3861981.jpeg?auto=compress&w=600",
    category: "Video & Animation",
    title: "I will create animated explainer videos",
    rating: 4.9,
    reviews: 89,
    author: {
      name: "Sarah Johnson",
      avatar: "https://randomuser.me/api/portraits/women/33.jpg",
    },
    price: 750,
  },
  {
    id: 16,
    image: "https://images.pexels.com/photos/3861982/pexels-photo-3861982.jpeg?auto=compress&w=600",
    category: "Programming & Tech",
    title: "I will develop custom web applications",
    rating: 4.7,
    reviews: 312,
    author: {
      name: "Michael Brown",
      avatar: "https://randomuser.me/api/portraits/men/28.jpg",
    },
    price: 1200,
  },
  {
    id: 17,
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=600&q=80",
    category: "Business",
    title: "I will create business plans and strategies",
    rating: 4.8,
    reviews: 145,
    author: {
      name: "Lisa Davis",
      avatar: "https://randomuser.me/api/portraits/women/41.jpg",
    },
    price: 300,
  },
  {
    id: 18,
    image: "https://images.pexels.com/photos/3861984/pexels-photo-3861984.jpeg?auto=compress&w=600",
    category: "Music & Audio",
    title: "I will compose original music for your project",
    rating: 4.9,
    reviews: 67,
    author: {
      name: "David Wilson",
      avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    },
    price: 200,
  },
  {
    id: 19,
    image: "https://images.pexels.com/photos/3861985/pexels-photo-3861985.jpeg?auto=compress&w=600",
    category: "Photography",
    title: "I will take professional product photos",
    rating: 4.8,
    reviews: 178,
    author: {
      name: "Anna Garcia",
      avatar: "https://randomuser.me/api/portraits/women/55.jpg",
    },
    price: 150,
  },
  {
    id: 20,
    image: "https://images.pexels.com/photos/3861986/pexels-photo-3861986.jpeg?auto=compress&w=600",
    category: "Marketing",
    title: "I will create email marketing campaigns",
    rating: 4.7,
    reviews: 234,
    author: {
      name: "Robert Taylor",
      avatar: "https://randomuser.me/api/portraits/men/37.jpg",
    },
    price: 180,
  },
  {
    id: 1,
    image: "https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Wanda Runo",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    price: 983,
  },
  {
    id: 2,
    image: "https://images.pexels.com/photos/1103970/pexels-photo-1103970.jpeg?auto=compress&w=600",
    category: "Art & Illustration",
    title: "I will create modern flat design illustration",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 3,
    image: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Sophie Lee",
      avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    },
    price: 983,
  },
  {
    id: 4,
    image: "https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  {
    id: 5,
    image: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Mia Chen",
      avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    price: 983,
  },
  {
    id: 6,
    image: "https://images.pexels.com/photos/3861972/pexels-photo-3861972.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Wanda Runo",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    price: 983,
  },
  {
    id: 7,
    image: "https://images.pexels.com/photos/3861973/pexels-photo-3861973.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 8,
    image: "https://images.pexels.com/photos/3861974/pexels-photo-3861974.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  {
    id: 9,
    image: "https://images.pexels.com/photos/3861975/pexels-photo-3861975.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Mia Chen",
      avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    price: 983,
  },
  {
    id: 10,
    image: "https://images.pexels.com/photos/3861976/pexels-photo-3861976.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Sophie Lee",
      avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    },
    price: 983,
  },
  {
    id: 11,
    image: "https://images.pexels.com/photos/3861977/pexels-photo-3861977.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 12,
    image: "https://images.pexels.com/photos/3861978/pexels-photo-3861978.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  // Additional services for load more functionality
  {
    id: 13,
    image: "https://images.pexels.com/photos/3861979/pexels-photo-3861979.jpeg?auto=compress&w=600",
    category: "Digital Marketing",
    title: "I will create social media marketing campaigns",
    rating: 4.9,
    reviews: 156,
    author: {
      name: "Emma Wilson",
      avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    },
    price: 450,
  },
  {
    id: 14,
    image: "https://images.pexels.com/photos/3861980/pexels-photo-3861980.jpeg?auto=compress&w=600",
    category: "Writing & Translation",
    title: "I will write professional content for your website",
    rating: 4.8,
    reviews: 203,
    author: {
      name: "James Smith",
      avatar: "https://randomuser.me/api/portraits/men/15.jpg",
    },
    price: 120,
  },
  {
    id: 15,
    image: "https://images.pexels.com/photos/3861981/pexels-photo-3861981.jpeg?auto=compress&w=600",
    category: "Video & Animation",
    title: "I will create animated explainer videos",
    rating: 4.9,
    reviews: 89,
    author: {
      name: "Sarah Johnson",
      avatar: "https://randomuser.me/api/portraits/women/33.jpg",
    },
    price: 750,
  },
  {
    id: 16,
    image: "https://images.pexels.com/photos/3861982/pexels-photo-3861982.jpeg?auto=compress&w=600",
    category: "Programming & Tech",
    title: "I will develop custom web applications",
    rating: 4.7,
    reviews: 312,
    author: {
      name: "Michael Brown",
      avatar: "https://randomuser.me/api/portraits/men/28.jpg",
    },
    price: 1200,
  },
  {
    id: 17,
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=600&q=80",
    category: "Business",
    title: "I will create business plans and strategies",
    rating: 4.8,
    reviews: 145,
    author: {
      name: "Lisa Davis",
      avatar: "https://randomuser.me/api/portraits/women/41.jpg",
    },
    price: 300,
  },
  {
    id: 18,
    image: "https://images.pexels.com/photos/3861984/pexels-photo-3861984.jpeg?auto=compress&w=600",
    category: "Music & Audio",
    title: "I will compose original music for your project",
    rating: 4.9,
    reviews: 67,
    author: {
      name: "David Wilson",
      avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    },
    price: 200,
  },
  {
    id: 19,
    image: "https://images.pexels.com/photos/3861985/pexels-photo-3861985.jpeg?auto=compress&w=600",
    category: "Photography",
    title: "I will take professional product photos",
    rating: 4.8,
    reviews: 178,
    author: {
      name: "Anna Garcia",
      avatar: "https://randomuser.me/api/portraits/women/55.jpg",
    },
    price: 150,
  },
  {
    id: 20,
    image: "https://images.pexels.com/photos/3861986/pexels-photo-3861986.jpeg?auto=compress&w=600",
    category: "Marketing",
    title: "I will create email marketing campaigns",
    rating: 4.7,
    reviews: 234,
    author: {
      name: "Robert Taylor",
      avatar: "https://randomuser.me/api/portraits/men/37.jpg",
    },
    price: 180,
  },
  {
    id: 1,
    image: "https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Wanda Runo",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    price: 983,
  },
  {
    id: 2,
    image: "https://images.pexels.com/photos/1103970/pexels-photo-1103970.jpeg?auto=compress&w=600",
    category: "Art & Illustration",
    title: "I will create modern flat design illustration",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 3,
    image: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Sophie Lee",
      avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    },
    price: 983,
  },
  {
    id: 4,
    image: "https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  {
    id: 5,
    image: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Mia Chen",
      avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    price: 983,
  },
  {
    id: 6,
    image: "https://images.pexels.com/photos/3861972/pexels-photo-3861972.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Wanda Runo",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    price: 983,
  },
  {
    id: 7,
    image: "https://images.pexels.com/photos/3861973/pexels-photo-3861973.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 8,
    image: "https://images.pexels.com/photos/3861974/pexels-photo-3861974.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  {
    id: 9,
    image: "https://images.pexels.com/photos/3861975/pexels-photo-3861975.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Mia Chen",
      avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    price: 983,
  },
  {
    id: 10,
    image: "https://images.pexels.com/photos/3861976/pexels-photo-3861976.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Sophie Lee",
      avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    },
    price: 983,
  },
  {
    id: 11,
    image: "https://images.pexels.com/photos/3861977/pexels-photo-3861977.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 12,
    image: "https://images.pexels.com/photos/3861978/pexels-photo-3861978.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  // Additional services for load more functionality
  {
    id: 13,
    image: "https://images.pexels.com/photos/3861979/pexels-photo-3861979.jpeg?auto=compress&w=600",
    category: "Digital Marketing",
    title: "I will create social media marketing campaigns",
    rating: 4.9,
    reviews: 156,
    author: {
      name: "Emma Wilson",
      avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    },
    price: 450,
  },
  {
    id: 14,
    image: "https://images.pexels.com/photos/3861980/pexels-photo-3861980.jpeg?auto=compress&w=600",
    category: "Writing & Translation",
    title: "I will write professional content for your website",
    rating: 4.8,
    reviews: 203,
    author: {
      name: "James Smith",
      avatar: "https://randomuser.me/api/portraits/men/15.jpg",
    },
    price: 120,
  },
  {
    id: 15,
    image: "https://images.pexels.com/photos/3861981/pexels-photo-3861981.jpeg?auto=compress&w=600",
    category: "Video & Animation",
    title: "I will create animated explainer videos",
    rating: 4.9,
    reviews: 89,
    author: {
      name: "Sarah Johnson",
      avatar: "https://randomuser.me/api/portraits/women/33.jpg",
    },
    price: 750,
  },
  {
    id: 16,
    image: "https://images.pexels.com/photos/3861982/pexels-photo-3861982.jpeg?auto=compress&w=600",
    category: "Programming & Tech",
    title: "I will develop custom web applications",
    rating: 4.7,
    reviews: 312,
    author: {
      name: "Michael Brown",
      avatar: "https://randomuser.me/api/portraits/men/28.jpg",
    },
    price: 1200,
  },
  {
    id: 17,
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=600&q=80",
    category: "Business",
    title: "I will create business plans and strategies",
    rating: 4.8,
    reviews: 145,
    author: {
      name: "Lisa Davis",
      avatar: "https://randomuser.me/api/portraits/women/41.jpg",
    },
    price: 300,
  },
  {
    id: 18,
    image: "https://images.pexels.com/photos/3861984/pexels-photo-3861984.jpeg?auto=compress&w=600",
    category: "Music & Audio",
    title: "I will compose original music for your project",
    rating: 4.9,
    reviews: 67,
    author: {
      name: "David Wilson",
      avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    },
    price: 200,
  },
  {
    id: 19,
    image: "https://images.pexels.com/photos/3861985/pexels-photo-3861985.jpeg?auto=compress&w=600",
    category: "Photography",
    title: "I will take professional product photos",
    rating: 4.8,
    reviews: 178,
    author: {
      name: "Anna Garcia",
      avatar: "https://randomuser.me/api/portraits/women/55.jpg",
    },
    price: 150,
  },
  {
    id: 20,
    image: "https://images.pexels.com/photos/3861986/pexels-photo-3861986.jpeg?auto=compress&w=600",
    category: "Marketing",
    title: "I will create email marketing campaigns",
    rating: 4.7,
    reviews: 234,
    author: {
      name: "Robert Taylor",
      avatar: "https://randomuser.me/api/portraits/men/37.jpg",
    },
    price: 180,
  },
  {
    id: 1,
    image: "https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Wanda Runo",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    price: 983,
  },
  {
    id: 2,
    image: "https://images.pexels.com/photos/1103970/pexels-photo-1103970.jpeg?auto=compress&w=600",
    category: "Art & Illustration",
    title: "I will create modern flat design illustration",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 3,
    image: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Sophie Lee",
      avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    },
    price: 983,
  },
  {
    id: 4,
    image: "https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  {
    id: 5,
    image: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Mia Chen",
      avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    price: 983,
  },
  {
    id: 6,
    image: "https://images.pexels.com/photos/3861972/pexels-photo-3861972.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Wanda Runo",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    price: 983,
  },
  {
    id: 7,
    image: "https://images.pexels.com/photos/3861973/pexels-photo-3861973.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 8,
    image: "https://images.pexels.com/photos/3861974/pexels-photo-3861974.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  {
    id: 9,
    image: "https://images.pexels.com/photos/3861975/pexels-photo-3861975.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Mia Chen",
      avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    price: 983,
  },
  {
    id: 10,
    image: "https://images.pexels.com/photos/3861976/pexels-photo-3861976.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Sophie Lee",
      avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    },
    price: 983,
  },
  {
    id: 11,
    image: "https://images.pexels.com/photos/3861977/pexels-photo-3861977.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 12,
    image: "https://images.pexels.com/photos/3861978/pexels-photo-3861978.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  // Additional services for load more functionality
  {
    id: 13,
    image: "https://images.pexels.com/photos/3861979/pexels-photo-3861979.jpeg?auto=compress&w=600",
    category: "Digital Marketing",
    title: "I will create social media marketing campaigns",
    rating: 4.9,
    reviews: 156,
    author: {
      name: "Emma Wilson",
      avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    },
    price: 450,
  },
  {
    id: 14,
    image: "https://images.pexels.com/photos/3861980/pexels-photo-3861980.jpeg?auto=compress&w=600",
    category: "Writing & Translation",
    title: "I will write professional content for your website",
    rating: 4.8,
    reviews: 203,
    author: {
      name: "James Smith",
      avatar: "https://randomuser.me/api/portraits/men/15.jpg",
    },
    price: 120,
  },
  {
    id: 15,
    image: "https://images.pexels.com/photos/3861981/pexels-photo-3861981.jpeg?auto=compress&w=600",
    category: "Video & Animation",
    title: "I will create animated explainer videos",
    rating: 4.9,
    reviews: 89,
    author: {
      name: "Sarah Johnson",
      avatar: "https://randomuser.me/api/portraits/women/33.jpg",
    },
    price: 750,
  },
  {
    id: 16,
    image: "https://images.pexels.com/photos/3861982/pexels-photo-3861982.jpeg?auto=compress&w=600",
    category: "Programming & Tech",
    title: "I will develop custom web applications",
    rating: 4.7,
    reviews: 312,
    author: {
      name: "Michael Brown",
      avatar: "https://randomuser.me/api/portraits/men/28.jpg",
    },
    price: 1200,
  },
  {
    id: 17,
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=600&q=80",
    category: "Business",
    title: "I will create business plans and strategies",
    rating: 4.8,
    reviews: 145,
    author: {
      name: "Lisa Davis",
      avatar: "https://randomuser.me/api/portraits/women/41.jpg",
    },
    price: 300,
  },
  {
    id: 18,
    image: "https://images.pexels.com/photos/3861984/pexels-photo-3861984.jpeg?auto=compress&w=600",
    category: "Music & Audio",
    title: "I will compose original music for your project",
    rating: 4.9,
    reviews: 67,
    author: {
      name: "David Wilson",
      avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    },
    price: 200,
  },
  {
    id: 19,
    image: "https://images.pexels.com/photos/3861985/pexels-photo-3861985.jpeg?auto=compress&w=600",
    category: "Photography",
    title: "I will take professional product photos",
    rating: 4.8,
    reviews: 178,
    author: {
      name: "Anna Garcia",
      avatar: "https://randomuser.me/api/portraits/women/55.jpg",
    },
    price: 150,
  },
  {
    id: 20,
    image: "https://images.pexels.com/photos/3861986/pexels-photo-3861986.jpeg?auto=compress&w=600",
    category: "Marketing",
    title: "I will create email marketing campaigns",
    rating: 4.7,
    reviews: 234,
    author: {
      name: "Robert Taylor",
      avatar: "https://randomuser.me/api/portraits/men/37.jpg",
    },
    price: 180,
  },
  {
    id: 1,
    image: "https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Wanda Runo",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    price: 983,
  },
  {
    id: 2,
    image: "https://images.pexels.com/photos/1103970/pexels-photo-1103970.jpeg?auto=compress&w=600",
    category: "Art & Illustration",
    title: "I will create modern flat design illustration",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 3,
    image: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Sophie Lee",
      avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    },
    price: 983,
  },
  {
    id: 4,
    image: "https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  {
    id: 5,
    image: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Mia Chen",
      avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    price: 983,
  },
  {
    id: 6,
    image: "https://images.pexels.com/photos/3861972/pexels-photo-3861972.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Wanda Runo",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    price: 983,
  },
  {
    id: 7,
    image: "https://images.pexels.com/photos/3861973/pexels-photo-3861973.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 8,
    image: "https://images.pexels.com/photos/3861974/pexels-photo-3861974.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  {
    id: 9,
    image: "https://images.pexels.com/photos/3861975/pexels-photo-3861975.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Mia Chen",
      avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    price: 983,
  },
  {
    id: 10,
    image: "https://images.pexels.com/photos/3861976/pexels-photo-3861976.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Sophie Lee",
      avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    },
    price: 983,
  },
  {
    id: 11,
    image: "https://images.pexels.com/photos/3861977/pexels-photo-3861977.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 12,
    image: "https://images.pexels.com/photos/3861978/pexels-photo-3861978.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  // Additional services for load more functionality
  {
    id: 13,
    image: "https://images.pexels.com/photos/3861979/pexels-photo-3861979.jpeg?auto=compress&w=600",
    category: "Digital Marketing",
    title: "I will create social media marketing campaigns",
    rating: 4.9,
    reviews: 156,
    author: {
      name: "Emma Wilson",
      avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    },
    price: 450,
  },
  {
    id: 14,
    image: "https://images.pexels.com/photos/3861980/pexels-photo-3861980.jpeg?auto=compress&w=600",
    category: "Writing & Translation",
    title: "I will write professional content for your website",
    rating: 4.8,
    reviews: 203,
    author: {
      name: "James Smith",
      avatar: "https://randomuser.me/api/portraits/men/15.jpg",
    },
    price: 120,
  },
  {
    id: 15,
    image: "https://images.pexels.com/photos/3861981/pexels-photo-3861981.jpeg?auto=compress&w=600",
    category: "Video & Animation",
    title: "I will create animated explainer videos",
    rating: 4.9,
    reviews: 89,
    author: {
      name: "Sarah Johnson",
      avatar: "https://randomuser.me/api/portraits/women/33.jpg",
    },
    price: 750,
  },
  {
    id: 16,
    image: "https://images.pexels.com/photos/3861982/pexels-photo-3861982.jpeg?auto=compress&w=600",
    category: "Programming & Tech",
    title: "I will develop custom web applications",
    rating: 4.7,
    reviews: 312,
    author: {
      name: "Michael Brown",
      avatar: "https://randomuser.me/api/portraits/men/28.jpg",
    },
    price: 1200,
  },
  {
    id: 17,
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=600&q=80",
    category: "Business",
    title: "I will create business plans and strategies",
    rating: 4.8,
    reviews: 145,
    author: {
      name: "Lisa Davis",
      avatar: "https://randomuser.me/api/portraits/women/41.jpg",
    },
    price: 300,
  },
  {
    id: 18,
    image: "https://images.pexels.com/photos/3861984/pexels-photo-3861984.jpeg?auto=compress&w=600",
    category: "Music & Audio",
    title: "I will compose original music for your project",
    rating: 4.9,
    reviews: 67,
    author: {
      name: "David Wilson",
      avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    },
    price: 200,
  },
  {
    id: 19,
    image: "https://images.pexels.com/photos/3861985/pexels-photo-3861985.jpeg?auto=compress&w=600",
    category: "Photography",
    title: "I will take professional product photos",
    rating: 4.8,
    reviews: 178,
    author: {
      name: "Anna Garcia",
      avatar: "https://randomuser.me/api/portraits/women/55.jpg",
    },
    price: 150,
  },
  {
    id: 20,
    image: "https://images.pexels.com/photos/3861986/pexels-photo-3861986.jpeg?auto=compress&w=600",
    category: "Marketing",
    title: "I will create email marketing campaigns",
    rating: 4.7,
    reviews: 234,
    author: {
      name: "Robert Taylor",
      avatar: "https://randomuser.me/api/portraits/men/37.jpg",
    },
    price: 180,
  },
  {
    id: 1,
    image: "https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Wanda Runo",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    price: 983,
  },
  {
    id: 2,
    image: "https://images.pexels.com/photos/1103970/pexels-photo-1103970.jpeg?auto=compress&w=600",
    category: "Art & Illustration",
    title: "I will create modern flat design illustration",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 3,
    image: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Sophie Lee",
      avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    },
    price: 983,
  },
  {
    id: 4,
    image: "https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  {
    id: 5,
    image: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Mia Chen",
      avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    price: 983,
  },
  {
    id: 6,
    image: "https://images.pexels.com/photos/3861972/pexels-photo-3861972.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Wanda Runo",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    price: 983,
  },
  {
    id: 7,
    image: "https://images.pexels.com/photos/3861973/pexels-photo-3861973.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 8,
    image: "https://images.pexels.com/photos/3861974/pexels-photo-3861974.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  {
    id: 9,
    image: "https://images.pexels.com/photos/3861975/pexels-photo-3861975.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Mia Chen",
      avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    price: 983,
  },
  {
    id: 10,
    image: "https://images.pexels.com/photos/3861976/pexels-photo-3861976.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Sophie Lee",
      avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    },
    price: 983,
  },
  {
    id: 11,
    image: "https://images.pexels.com/photos/3861977/pexels-photo-3861977.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 12,
    image: "https://images.pexels.com/photos/3861978/pexels-photo-3861978.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  // Additional services for load more functionality
  {
    id: 13,
    image: "https://images.pexels.com/photos/3861979/pexels-photo-3861979.jpeg?auto=compress&w=600",
    category: "Digital Marketing",
    title: "I will create social media marketing campaigns",
    rating: 4.9,
    reviews: 156,
    author: {
      name: "Emma Wilson",
      avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    },
    price: 450,
  },
  {
    id: 14,
    image: "https://images.pexels.com/photos/3861980/pexels-photo-3861980.jpeg?auto=compress&w=600",
    category: "Writing & Translation",
    title: "I will write professional content for your website",
    rating: 4.8,
    reviews: 203,
    author: {
      name: "James Smith",
      avatar: "https://randomuser.me/api/portraits/men/15.jpg",
    },
    price: 120,
  },
  {
    id: 15,
    image: "https://images.pexels.com/photos/3861981/pexels-photo-3861981.jpeg?auto=compress&w=600",
    category: "Video & Animation",
    title: "I will create animated explainer videos",
    rating: 4.9,
    reviews: 89,
    author: {
      name: "Sarah Johnson",
      avatar: "https://randomuser.me/api/portraits/women/33.jpg",
    },
    price: 750,
  },
  {
    id: 16,
    image: "https://images.pexels.com/photos/3861982/pexels-photo-3861982.jpeg?auto=compress&w=600",
    category: "Programming & Tech",
    title: "I will develop custom web applications",
    rating: 4.7,
    reviews: 312,
    author: {
      name: "Michael Brown",
      avatar: "https://randomuser.me/api/portraits/men/28.jpg",
    },
    price: 1200,
  },
  {
    id: 17,
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=600&q=80",
    category: "Business",
    title: "I will create business plans and strategies",
    rating: 4.8,
    reviews: 145,
    author: {
      name: "Lisa Davis",
      avatar: "https://randomuser.me/api/portraits/women/41.jpg",
    },
    price: 300,
  },
  {
    id: 18,
    image: "https://images.pexels.com/photos/3861984/pexels-photo-3861984.jpeg?auto=compress&w=600",
    category: "Music & Audio",
    title: "I will compose original music for your project",
    rating: 4.9,
    reviews: 67,
    author: {
      name: "David Wilson",
      avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    },
    price: 200,
  },
  {
    id: 19,
    image: "https://images.pexels.com/photos/3861985/pexels-photo-3861985.jpeg?auto=compress&w=600",
    category: "Photography",
    title: "I will take professional product photos",
    rating: 4.8,
    reviews: 178,
    author: {
      name: "Anna Garcia",
      avatar: "https://randomuser.me/api/portraits/women/55.jpg",
    },
    price: 150,
  },
  {
    id: 20,
    image: "https://images.pexels.com/photos/3861986/pexels-photo-3861986.jpeg?auto=compress&w=600",
    category: "Marketing",
    title: "I will create email marketing campaigns",
    rating: 4.7,
    reviews: 234,
    author: {
      name: "Robert Taylor",
      avatar: "https://randomuser.me/api/portraits/men/37.jpg",
    },
    price: 180,
  },
  {
    id: 1,
    image: "https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Wanda Runo",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    price: 983,
  },
  {
    id: 2,
    image: "https://images.pexels.com/photos/1103970/pexels-photo-1103970.jpeg?auto=compress&w=600",
    category: "Art & Illustration",
    title: "I will create modern flat design illustration",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 3,
    image: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Sophie Lee",
      avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    },
    price: 983,
  },
  {
    id: 4,
    image: "https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  {
    id: 5,
    image: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Mia Chen",
      avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    price: 983,
  },
  {
    id: 6,
    image: "https://images.pexels.com/photos/3861972/pexels-photo-3861972.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Wanda Runo",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    price: 983,
  },
  {
    id: 7,
    image: "https://images.pexels.com/photos/3861973/pexels-photo-3861973.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 8,
    image: "https://images.pexels.com/photos/3861974/pexels-photo-3861974.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  {
    id: 9,
    image: "https://images.pexels.com/photos/3861975/pexels-photo-3861975.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Mia Chen",
      avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    price: 983,
  },
  {
    id: 10,
    image: "https://images.pexels.com/photos/3861976/pexels-photo-3861976.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Sophie Lee",
      avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    },
    price: 983,
  },
  {
    id: 11,
    image: "https://images.pexels.com/photos/3861977/pexels-photo-3861977.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 12,
    image: "https://images.pexels.com/photos/3861978/pexels-photo-3861978.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  // Additional services for load more functionality
  {
    id: 13,
    image: "https://images.pexels.com/photos/3861979/pexels-photo-3861979.jpeg?auto=compress&w=600",
    category: "Digital Marketing",
    title: "I will create social media marketing campaigns",
    rating: 4.9,
    reviews: 156,
    author: {
      name: "Emma Wilson",
      avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    },
    price: 450,
  },
  {
    id: 14,
    image: "https://images.pexels.com/photos/3861980/pexels-photo-3861980.jpeg?auto=compress&w=600",
    category: "Writing & Translation",
    title: "I will write professional content for your website",
    rating: 4.8,
    reviews: 203,
    author: {
      name: "James Smith",
      avatar: "https://randomuser.me/api/portraits/men/15.jpg",
    },
    price: 120,
  },
  {
    id: 15,
    image: "https://images.pexels.com/photos/3861981/pexels-photo-3861981.jpeg?auto=compress&w=600",
    category: "Video & Animation",
    title: "I will create animated explainer videos",
    rating: 4.9,
    reviews: 89,
    author: {
      name: "Sarah Johnson",
      avatar: "https://randomuser.me/api/portraits/women/33.jpg",
    },
    price: 750,
  },
  {
    id: 16,
    image: "https://images.pexels.com/photos/3861982/pexels-photo-3861982.jpeg?auto=compress&w=600",
    category: "Programming & Tech",
    title: "I will develop custom web applications",
    rating: 4.7,
    reviews: 312,
    author: {
      name: "Michael Brown",
      avatar: "https://randomuser.me/api/portraits/men/28.jpg",
    },
    price: 1200,
  },
  {
    id: 17,
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=600&q=80",
    category: "Business",
    title: "I will create business plans and strategies",
    rating: 4.8,
    reviews: 145,
    author: {
      name: "Lisa Davis",
      avatar: "https://randomuser.me/api/portraits/women/41.jpg",
    },
    price: 300,
  },
  {
    id: 18,
    image: "https://images.pexels.com/photos/3861984/pexels-photo-3861984.jpeg?auto=compress&w=600",
    category: "Music & Audio",
    title: "I will compose original music for your project",
    rating: 4.9,
    reviews: 67,
    author: {
      name: "David Wilson",
      avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    },
    price: 200,
  },
  {
    id: 19,
    image: "https://images.pexels.com/photos/3861985/pexels-photo-3861985.jpeg?auto=compress&w=600",
    category: "Photography",
    title: "I will take professional product photos",
    rating: 4.8,
    reviews: 178,
    author: {
      name: "Anna Garcia",
      avatar: "https://randomuser.me/api/portraits/women/55.jpg",
    },
    price: 150,
  },
  {
    id: 20,
    image: "https://images.pexels.com/photos/3861986/pexels-photo-3861986.jpeg?auto=compress&w=600",
    category: "Marketing",
    title: "I will create email marketing campaigns",
    rating: 4.7,
    reviews: 234,
    author: {
      name: "Robert Taylor",
      avatar: "https://randomuser.me/api/portraits/men/37.jpg",
    },
    price: 180,
  },
  {
    id: 1,
    image: "https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Wanda Runo",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    price: 983,
  },
  {
    id: 2,
    image: "https://images.pexels.com/photos/1103970/pexels-photo-1103970.jpeg?auto=compress&w=600",
    category: "Art & Illustration",
    title: "I will create modern flat design illustration",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 3,
    image: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Sophie Lee",
      avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    },
    price: 983,
  },
  {
    id: 4,
    image: "https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  {
    id: 5,
    image: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Mia Chen",
      avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    price: 983,
  },
  {
    id: 6,
    image: "https://images.pexels.com/photos/3861972/pexels-photo-3861972.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Wanda Runo",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    price: 983,
  },
  {
    id: 7,
    image: "https://images.pexels.com/photos/3861973/pexels-photo-3861973.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 8,
    image: "https://images.pexels.com/photos/3861974/pexels-photo-3861974.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  {
    id: 9,
    image: "https://images.pexels.com/photos/3861975/pexels-photo-3861975.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Mia Chen",
      avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    price: 983,
  },
  {
    id: 10,
    image: "https://images.pexels.com/photos/3861976/pexels-photo-3861976.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will design modern websites in figma or adobe xd",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Sophie Lee",
      avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    },
    price: 983,
  },
  {
    id: 11,
    image: "https://images.pexels.com/photos/3861977/pexels-photo-3861977.jpeg?auto=compress&w=600",
    category: "Design & Creative",
    title: "I will build a fully responsive design in HTML,CSS, bootstrap...",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Ali Tufan",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    price: 983,
  },
  {
    id: 12,
    image: "https://images.pexels.com/photos/3861978/pexels-photo-3861978.jpeg?auto=compress&w=600",
    category: "Web & App Design",
    title: "I will do mobile app development for ios and android",
    rating: 4.82,
    reviews: 94,
    author: {
      name: "Carlos Vega",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    price: 983,
  },
  // Additional services for load more functionality
  {
    id: 13,
    image: "https://images.pexels.com/photos/3861979/pexels-photo-3861979.jpeg?auto=compress&w=600",
    category: "Digital Marketing",
    title: "I will create social media marketing campaigns",
    rating: 4.9,
    reviews: 156,
    author: {
      name: "Emma Wilson",
      avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    },
    price: 450,
  },
  {
    id: 14,
    image: "https://images.pexels.com/photos/3861980/pexels-photo-3861980.jpeg?auto=compress&w=600",
    category: "Writing & Translation",
    title: "I will write professional content for your website",
    rating: 4.8,
    reviews: 203,
    author: {
      name: "James Smith",
      avatar: "https://randomuser.me/api/portraits/men/15.jpg",
    },
    price: 120,
  },
  {
    id: 15,
    image: "https://images.pexels.com/photos/3861981/pexels-photo-3861981.jpeg?auto=compress&w=600",
    category: "Video & Animation",
    title: "I will create animated explainer videos",
    rating: 4.9,
    reviews: 89,
    author: {
      name: "Sarah Johnson",
      avatar: "https://randomuser.me/api/portraits/women/33.jpg",
    },
    price: 750,
  },
  {
    id: 16,
    image: "https://images.pexels.com/photos/3861982/pexels-photo-3861982.jpeg?auto=compress&w=600",
    category: "Programming & Tech",
    title: "I will develop custom web applications",
    rating: 4.7,
    reviews: 312,
    author: {
      name: "Michael Brown",
      avatar: "https://randomuser.me/api/portraits/men/28.jpg",
    },
    price: 1200,
  },
  {
    id: 17,
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=600&q=80",
    category: "Business",
    title: "I will create business plans and strategies",
    rating: 4.8,
    reviews: 145,
    author: {
      name: "Lisa Davis",
      avatar: "https://randomuser.me/api/portraits/women/41.jpg",
    },
    price: 300,
  },
  {
    id: 18,
    image: "https://images.pexels.com/photos/3861984/pexels-photo-3861984.jpeg?auto=compress&w=600",
    category: "Music & Audio",
    title: "I will compose original music for your project",
    rating: 4.9,
    reviews: 67,
    author: {
      name: "David Wilson",
      avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    },
    price: 200,
  },
  {
    id: 19,
    image: "https://images.pexels.com/photos/3861985/pexels-photo-3861985.jpeg?auto=compress&w=600",
    category: "Photography",
    title: "I will take professional product photos",
    rating: 4.8,
    reviews: 178,
    author: {
      name: "Anna Garcia",
      avatar: "https://randomuser.me/api/portraits/women/55.jpg",
    },
    price: 150,
  },
  {
    id: 20,
    image: "https://images.pexels.com/photos/3861986/pexels-photo-3861986.jpeg?auto=compress&w=600",
    category: "Marketing",
    title: "I will create email marketing campaigns",
    rating: 4.7,
    reviews: 234,
    author: {
      name: "Robert Taylor",
      avatar: "https://randomuser.me/api/portraits/men/37.jpg",
    },
    price: 180,
  },
]

const allServices = baseServices.map(s => ({ ...s, subCategory: pickSubCategory(s.category, s.id) }))

// Map main menu categories to the categories used in the base services
const CATEGORY_TO_SERVICE_CATEGORIES: Record<string, string[]> = {
  "All Categories": [],
  Trending: [],
  "Trending Services": [],
  "Graphics & Design": ["Design & Creative", "Art & Illustration", "Web & App Design"],
  "Digital Marketing": ["Digital Marketing", "Marketing"],
  "Writing & Translation": ["Writing & Translation"],
  "Video & Animation": ["Video & Animation"],
  "Music & Audio": ["Music & Audio"],
  "Programming & Tech": ["Programming & Tech", "Web & App Design"],
  Business: ["Business"],
  Lifestyle: ["Lifestyle"],
  Photography: ["Photography"],
}

export function ServiceGrid() {
  const searchParams = useSearchParams()
  const [visibleCount, setVisibleCount] = useState(40) // Initially show 8 services
  const [isLoading, setIsLoading] = useState(false)

  const selectedCategoryRaw = searchParams.get("category") || "All Categories"
  const selectedSubCategoryRaw = searchParams.get("sub-category") || ""
  const selectedCategory = decodeURIComponent(selectedCategoryRaw)
  const selectedSubCategory = decodeURIComponent(selectedSubCategoryRaw)

  const filtered = useMemo(() => {
    const allowed = CATEGORY_TO_SERVICE_CATEGORIES[selectedCategory]
    return allServices.filter(s => {
      const categoryMatch = !allowed || allowed.length === 0 ? true : allowed.includes(s.category)
      const subMatch = selectedSubCategory ? s.subCategory === selectedSubCategory : true
      return categoryMatch && subMatch
    })
  }, [selectedCategory, selectedSubCategory])

  // Reset visible count when filters change for better UX
  useEffect(() => {
    setVisibleCount(40)
  }, [selectedCategory, selectedSubCategory])

  const services = filtered.slice(0, visibleCount)
  const hasMore = visibleCount < filtered.length

  const handleLoadMore = () => {
    setIsLoading(true)
    
    // Simulate loading delay for better UX
    setTimeout(() => {
      setVisibleCount(prev => Math.min(prev + 32, filtered.length))
      setIsLoading(false)
    }, 800)
  }

  return (
    <div className="max-w-7xl mx-auto  lg:px-0  my-8">


      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 sm:gap-6 mb-8 sm:mb-12">
        {services.map((service,index) => (
          <ServiceCard key={index} service={service} />
        ))}
      </div>
      
      {/* Load More Button */}
      {hasMore && (
        <div className="text-center">
          <Button
            onClick={handleLoadMore}
            disabled={isLoading}
            className=" text-white dark:text-gray-900 px-6 py-2 rounded-md"
          >
            {isLoading ? "Loading..." : "Load More"}
          </Button>
        </div>
      )}
      
      {/* Show message when all services are loaded */}
      {!hasMore && allServices.length > 8 && (
        <div className="text-center py-8">
          <p className="text-gray-500 dark:text-gray-400 text-sm">
            All {allServices.length} services have been loaded
          </p>
        </div>
      )}
    </div>
  )
}
